version: '3.8'

services:
  web:
    build: .
    command: python run.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: flaskblog
      POSTGRES_USER: sta
      POSTGRES_PASSWORD: sta123
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
